# Generated by Django 4.2.21 on 2025-05-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_customer_qq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="qq",
        ),
    ]
